/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threattimeshift;


import java.awt.Color;
import java.io.*;
import javax.swing.JFileChooser;
import java.io.File; 
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author James
 */
public class TimeShift extends javax.swing.JFrame {

    /**
     * Creates new form TimeShift
     */
    public TimeShift() {
        //this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        initComponents();
        jLabel3.setVisible(false);
    }
    
    public void openDialog(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileBTN = new javax.swing.JButton();
        outputFileLocationBTN = new javax.swing.JButton();
        inputFileText = new javax.swing.JTextField();
        outputText = new javax.swing.JTextField();
        FileName = new javax.swing.JTextField();
        runBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TimeToAdjust = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Threat Time Shift");

        inputFileBTN.setText("Input File");
        inputFileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileBTNActionPerformed(evt);
            }
        });

        outputFileLocationBTN.setText("Output File Location");
        outputFileLocationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileLocationBTNActionPerformed(evt);
            }
        });

        inputFileText.setEditable(false);
        inputFileText.setEnabled(false);

        outputText.setEditable(false);
        outputText.setEnabled(false);

        FileName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FileNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FileNameFocusLost(evt);
            }
        });

        runBTN.setText("Run");
        runBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBTNActionPerformed(evt);
            }
        });

        CancelBTN.setText("Cancel");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("New File Name");

        TimeToAdjust.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TimeToAdjustFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TimeToAdjustFocusLost(evt);
            }
        });

        jLabel2.setText("Time to adjust");

        jLabel3.setFont(new java.awt.Font("Marlett", 1, 24)); // NOI18N
        jLabel3.setText("Files Done!");
        jLabel3.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputFileBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outputFileLocationBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputText)
                            .addComponent(inputFileText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TimeToAdjust, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 347, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(runBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelBTN)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputFileBTN)
                    .addComponent(inputFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLocationBTN)
                    .addComponent(outputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeToAdjust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBTN)
                    .addComponent(runBTN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileBTNActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("dat File","dat");
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            inputFileText.setText(selectedFile.toString());
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_inputFileBTNActionPerformed

    private void outputFileLocationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileLocationBTNActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("dat File","dat");
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            outputText.setText(selectedFile.toString());
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_outputFileLocationBTNActionPerformed

    private void FileNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FileNameFocusLost
        if(!FileName.getText().contains(".dat")){
            FileName.setText(FileName.getText().concat(".dat"));
        }
    }//GEN-LAST:event_FileNameFocusLost

    private void FileNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FileNameFocusGained
        FileName.selectAll();
    }//GEN-LAST:event_FileNameFocusGained

    private void TimeToAdjustFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeToAdjustFocusGained
        TimeToAdjust.selectAll();
    }//GEN-LAST:event_TimeToAdjustFocusGained

    private void TimeToAdjustFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeToAdjustFocusLost
        try{
            Double.parseDouble(TimeToAdjust.getText());
        }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "You did not enter a number","Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TimeToAdjustFocusLost

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        this.dispose();
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void runBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBTNActionPerformed
        String line = null;
        ArrayList arrayDouble = new ArrayList();
        String tab = "\t";
        String NewLine = "\n";
        try{
            FileReader fileReader = new FileReader(inputFileText.getText());
            BufferedReader reader = new BufferedReader(fileReader);
            File file = new File(outputText.getText().concat("/").concat(FileName.getText()));
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            while((line = reader.readLine()) != null){
                String array[] = line.trim().split("\\s|\\t");
                for(int i = 0; i < array.length; i++){
                    if(array[i].isEmpty() || array[i].equals("")){
                        continue;
                    }
                    arrayDouble.add(Double.parseDouble(array[i]));
                    if(i == 0){
                        double time = (double)(arrayDouble.get(i)) + Double.parseDouble(TimeToAdjust.getText());
                        writer.write(tab);
                        writer.write(String.valueOf(time));
                        writer.write(tab);
                    }else{
                        writer.write(array[i]);
                        writer.write(tab);
                    }   
                }
                writer.write(NewLine);
                arrayDouble.clear();
                
        
            }
            
            writer.close();
            reader.close();
            jLabel3.setVisible(true);
            jLabel3.setForeground(Color.ORANGE);
        }catch(FileNotFoundException ex){
            System.out.println("Unable to open file '" + 
                inputFileText.getText() + "'");
        }catch(IOException ex) {
            System.out.println("Error reading file '"  + inputFileText.getText() + "'"); 
        }
       
    }//GEN-LAST:event_runBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBTN;
    private javax.swing.JTextField FileName;
    private javax.swing.JTextField TimeToAdjust;
    private javax.swing.JButton inputFileBTN;
    private javax.swing.JTextField inputFileText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton outputFileLocationBTN;
    private javax.swing.JTextField outputText;
    private javax.swing.JButton runBTN;
    // End of variables declaration//GEN-END:variables
}
